import type { Claim } from '../types/claim'
import type { Item } from '../types/item'
import type { AuthUser, User } from '../types/user'
// DATOS DE EJEMPLO. Es la única fuente de datos falsos del proyecto:
// alimenta los mocks de la web y (más adelante) los emuladores de Firebase.
// Son personas y objetos inventados.

export interface SeedData {
  accounts: AuthUser[] // cuentas con las que se puede "entrar" en modo de ejemplo
  users: User[]
  items: Item[]
  itemHiddenDetails: Record<string, string> // id del objeto → detalles ocultos
  claims: Claim[]
}
export const seed: SeedData = {
  accounts: [
    { id: 'user-lucia', email: 'lucia@example.com', displayName: 'Lucía Martín' },
  ],
  users: [
    { id: 'user-lucia', displayName: 'Lucía Martín', city: 'Madrid', createdAt: '2026-08-01T09:00:00.000Z' },
    { id: 'user-carlos', displayName: 'Carlos Ruiz', city: 'Valencia', createdAt: '2026-08-03T09:00:00.000Z' },
    { id: 'user-aina', displayName: 'Aina Ferrer', city: 'Barcelona', createdAt: '2026-08-10T09:00:00.000Z' },
    { id: 'user-mikel', displayName: 'Mikel Etxeberria', city: 'Bilbao', createdAt: '2026-08-12T09:00:00.000Z' },
    { id: 'user-elena', displayName: 'Elena Vega', city: 'Madrid', createdAt: '2026-08-15T09:00:00.000Z' },
    { id: 'user-david', displayName: 'David Pastor', city: 'Sevilla', createdAt: '2026-08-18T09:00:00.000Z' },
  ],
  items: [
    // 3 Objetos publicados por Lucía Martín (Mi usuario)
    {
      id: 'item-wallet',
      type: 'found',
      title: 'Cartera marrón de piel artesanal',
      description: 'Encontrada bajo la lluvia en un banco del Parque del Retiro durante el festival de poesía. Tenía dentro una carta doblada escrita a mano con tinta azul y un billete antiguo de metro.',
      category: 'wallets-bags',
      photos: ['/items/wallet.jpg'],
      city: 'Madrid',
      locationText: 'Parque del Retiro, cerca del estanque del Palacio de Cristal',
      date: '2026-09-10T17:30:00.000Z',
      status: 'published',
      createdBy: 'user-lucia',
      createdByName: 'Lucía Martín',
      createdAt: '2026-09-10T19:00:00.000Z',
      updatedAt: '2026-09-10T19:00:00.000Z',
    },
    {
      id: 'item-camera',
      type: 'found',
      title: 'Cámara réflex analógica vintage',
      description: 'Olvidada en una cafetería de Malasaña después de un concierto. El carrete aún tiene fotos por revelar y la correa tiene parches bordados de distintas ciudades europeas.',
      category: 'electronics',
      photos: ['/items/camera.jpg'],
      city: 'Madrid',
      locationText: 'Cafetería La Palma, Barrio de Malasaña',
      date: '2026-09-11T21:00:00.000Z',
      status: 'published',
      createdBy: 'user-lucia',
      createdByName: 'Lucía Martín',
      createdAt: '2026-09-11T22:30:00.000Z',
      updatedAt: '2026-09-11T22:30:00.000Z',
    },
    {
      id: 'item-keys',
      type: 'found',
      title: 'Manojo de llaves con llavero de latón',
      description: 'Encontrado en el suelo junto al andén de la estación de metro Colón. Incluye tres llaves de seguridad y una llave antigua dorada de aspecto histórico.',
      category: 'keys',
      photos: ['/items/keys.jpg'],
      city: 'Madrid',
      locationText: 'Estación de metro Colón, andén línea 4',
      date: '2026-09-12T08:15:00.000Z',
      status: 'published',
      createdBy: 'user-lucia',
      createdByName: 'Lucía Martín',
      createdAt: '2026-09-12T09:00:00.000Z',
      updatedAt: '2026-09-12T09:00:00.000Z',
    },

    // 7 Objetos publicados por otros miembros de la comunidad (Para que Lucía pueda reclamarlos)
    {
      id: 'item-watch',
      type: 'found',
      title: 'Reloj de pulsera con correa de cuero',
      description: 'Hallado en un banco de madera del parque del Turia tras la feria del libro. Un reloj elegante con mecanismo visible que sigue funcionando perfectamente.',
      category: 'jewelry',
      photos: ['/items/watch.jpg'],
      city: 'Valencia',
      locationText: 'Jardín del Turia, zona cercana al parque Gulliver',
      date: '2026-09-13T11:00:00.000Z',
      status: 'published',
      createdBy: 'user-carlos',
      createdByName: 'Carlos Ruiz',
      createdAt: '2026-09-13T12:00:00.000Z',
      updatedAt: '2026-09-13T12:00:00.000Z',
    },
    {
      id: 'item-glasses',
      type: 'found',
      title: 'Gafas de sol en funda de cuero',
      description: 'Dejadas en la mesa de una terraza en el Paseo Marítimo de la Barceloneta. Tienen patillas metálicas y la funda rígida está conservada impecable.',
      category: 'glasses',
      photos: ['/items/glasses.jpg'],
      city: 'Barcelona',
      locationText: 'Paseo Marítimo de la Barceloneta, junto a las duchas',
      date: '2026-09-14T16:00:00.000Z',
      status: 'published',
      createdBy: 'user-aina',
      createdByName: 'Aina Ferrer',
      createdAt: '2026-09-14T17:30:00.000Z',
      updatedAt: '2026-09-14T17:30:00.000Z',
    },
    {
      id: 'item-backpack',
      type: 'found',
      title: 'Mochila técnica de montaña',
      description: 'Olvidada en la parada de autobús hacia los Picos de Europa un domingo por la tarde. Mochila impermeable verde militar con mosquetones en las asas.',
      category: 'sports',
      photos: ['/items/backpack.jpg'],
      city: 'Bilbao',
      locationText: 'Estación de autobuses Termibus, darsena 14',
      date: '2026-09-15T19:00:00.000Z',
      status: 'published',
      createdBy: 'user-mikel',
      createdByName: 'Mikel Etxeberria',
      createdAt: '2026-09-15T20:00:00.000Z',
      updatedAt: '2026-09-15T20:00:00.000Z',
    },
    {
      id: 'item-guitar',
      type: 'found',
      title: 'Guitarra acústica clásica en funda',
      description: 'Localizada en el vagón de tren de Cercanías. La persona que la llevaba se bajó con prisas. La guitarra está impecable y desprende aroma a madera de cedro.',
      category: 'other',
      photos: ['/items/guitar.jpg'],
      city: 'Madrid',
      locationText: 'Tren Cercanías C-4, trayecto Atocha – Cantoblanco',
      date: '2026-09-16T10:30:00.000Z',
      status: 'published',
      createdBy: 'user-elena',
      createdByName: 'Elena Vega',
      createdAt: '2026-09-16T12:00:00.000Z',
      updatedAt: '2026-09-16T12:00:00.000Z',
    },
    {
      id: 'item-headphones',
      type: 'found',
      title: 'Auriculares inalámbricos en estuche',
      description: 'Caídos en un sillón de la biblioteca pública durante la semana de exámenes. El estuche de carga es blanco mate y tiene mucha carga restante.',
      category: 'electronics',
      photos: ['/items/headphones.jpg'],
      city: 'Bilbao',
      locationText: 'Biblioteca Central de Deusto, 2ª planta sala de estudio',
      date: '2026-09-17T18:45:00.000Z',
      status: 'published',
      createdBy: 'user-david',
      createdByName: 'David Pastor',
      createdAt: '2026-09-17T19:30:00.000Z',
      updatedAt: '2026-09-17T19:30:00.000Z',
    },
    {
      id: 'item-notebook',
      type: 'found',
      title: 'Carpeta de ilustraciones y acuarelas',
      description: 'Encontrada en un banco de piedra frente a la catedral. Contiene láminas dibujadas a mano con edificios y paisajes de la ciudad.',
      category: 'documents',
      photos: ['/items/notebook.jpg'],
      city: 'Barcelona',
      locationText: 'Plaza de la Catedral, cerca de las escaleras principales',
      date: '2026-09-18T13:20:00.000Z',
      status: 'published',
      createdBy: 'user-aina',
      createdByName: 'Aina Ferrer',
      createdAt: '2026-09-18T14:00:00.000Z',
      updatedAt: '2026-09-18T14:00:00.000Z',
    },
    {
      id: 'item-jacket',
      type: 'found',
      title: 'Cazadora de cuero estilo vintage',
      description: 'Olvidada en el perchero de una cafetería tras una tarde de lluvia. Talla mediana, cuero marrón oscuro con forro interior de franela a cuadros.',
      category: 'clothing',
      photos: ['/items/jacket.jpg'],
      city: 'Bilbao',
      locationText: 'Café Iruña, Casco Viejo',
      date: '2026-09-19T20:10:00.000Z',
      status: 'published',
      createdBy: 'user-mikel',
      createdByName: 'Mikel Etxeberria',
      createdAt: '2026-09-19T21:00:00.000Z',
      updatedAt: '2026-09-19T21:00:00.000Z',
    },
  ],
  itemHiddenDetails: {
    'item-wallet': 'En el bolsillo secreto del forro hay una entrada de cine de 2018 y una foto en blanco y negro de dos ancianos sonriendo.',
    'item-camera': 'La tapa del objetivo por dentro lleva una pequeña pegatina holográfica de Pink Floyd y el número de serie termina en 88.',
    'item-keys': 'El llavero metálico de latón tiene grabado por una cara las iniciales "A&M" y la fecha "12-05-2015".',
    'item-watch': 'Por la parte trasera de la caja tiene grabado en letra cursiva "25 años juntos" y una pequeña marca de rasguño cerca de la corona.',
    'item-glasses': 'Dentro de la funda rígida hay una pequeña gamuza limpia-cristales azul marino con el nombre de una óptica de San Sebastián.',
    'item-backpack': 'En el bolsillo superior impermeable hay un cuaderno pequeño con anotaciones de avistamiento de aves y una toalla amarilla.',
    'item-guitar': 'La cejuela es de hueso tallado y la etiqueta interior de madera lleva la firma del luthier "García & Hijos, Córdoba 1999".',
    'item-headphones': 'La base de la funda por la parte inferior tiene grabado a láser la frase "Never Stop Learning" y el usuario @alex_v2.',
    'item-notebook': 'En la primera página hay una firma con el nombre "Sofía B." y una dedicatoria escrita a lápiz que dice "Para quien busque inspiración".',
    'item-jacket': 'El bolsillo interior derecho conserva la entrada doblada de un museo de bellas artes de 2025 y un caramelo de menta sin abrir.',
  },
  claims: [
    // 1. Reclamación RECIBIDA por Lucía (alguien de la comunidad reclama la Cartera que Lucía publicó)
    {
      id: 'claim-wallet-incoming',
      itemId: 'item-wallet',
      itemTitle: 'Cartera marrón de piel artesanal',
      itemOwnerId: 'user-lucia',
      claimantId: 'user-mateo',
      claimantContact: { name: 'Mateo Fernández', email: 'mateo.f@example.com' },
      ownerContact: { name: 'Lucía Martín', email: 'lucia@example.com' },
      proof: 'En el bolsillo secreto del forro llevo una foto en blanco y negro de mis abuelos y una entrada antigua de cine.',
      status: 'pending',
      createdAt: '2026-09-16T12:00:00.000Z',
    },
    // 2. Reclamación ENVIADA por Lucía (Lucía reclama el Reloj que publicó Carlos Ruiz)
    {
      id: 'claim-watch-outgoing',
      itemId: 'item-watch',
      itemTitle: 'Reloj de pulsera con correa de cuero',
      itemOwnerId: 'user-carlos',
      claimantId: 'user-lucia',
      claimantContact: { name: 'Lucía Martín', email: 'lucia@example.com' },
      ownerContact: { name: 'Carlos Ruiz', email: 'carlos@example.com' },
      proof: 'Por la parte trasera del reloj tiene grabado "25 años juntos" y un rasguño fino cerca de la corona.',
      status: 'pending',
      createdAt: '2026-09-17T14:30:00.000Z',
    },
  ],
}

